# based on the template from
# https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml

image: maven:3.6-jdk-11

cache:
  paths:
    - .m2/repository

# For merge requests do not `deploy` but only run `verify`.
.verify: &verify
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS generate-sources'
    - 'mvn $MAVEN_CLI_OPTS verify'
    - 'mvn -Doxygen.version=23 $MAVEN_CLI_OPTS clean verify'
    - 'mvn -Doxygen.version=24 $MAVEN_CLI_OPTS clean verify'
    - 'mvn -Doxygen.version=25 $MAVEN_CLI_OPTS clean verify'
  except:
    - master

# Verify merge requests
verify:jdk11:
  <<: *verify

# deploy using .gitlab-ci_settings.xml as maven settings
# see https://gitlab.com/help/user/packages/maven_repository/index.md#creating-maven-packages-with-gitlab-cicd-using-maven
deploy:jdk11:
  script:
    - 'mvn generate-sources -s .gitlab-ci_settings.xml'
    - 'mvn verify -s .gitlab-ci_settings.xml'
    - 'echo "location of local maven repository:"'
    - 'mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout'
  artifacts:
    paths:
      - grammar/target
      - xpath-extension/target
      - saxon/target
  only:
    - master
    - tags

pages:
  stage: deploy
  script:
    - mkdir -p public
    - ls -la
    - mvn -Doxygen.version=23 $MAVEN_CLI_OPTS clean verify
    - cp -v oxygen/target/*-plugin.jar public/
    - mvn -Doxygen.version=24 $MAVEN_CLI_OPTS clean verify
    - cp -v oxygen/target/*-plugin.jar public/
    - mvn -Doxygen.version=25 $MAVEN_CLI_OPTS clean verify
    - cp -v oxygen/target/*-plugin.jar public/
    - cp -v target/generated-resources/xml/xslt/descriptor.xml public/
    - ls -la public
  artifacts:
    paths:
      - public
  only:
    # https://gitlab.com/gitlab-org/gitlab-foss/-/issues/27818
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+$/
